from typing import Any

class BeautifulSoup:
    def __init__(self, markup: Any = ..., features: str | None = ..., *args: Any, **kwargs: Any) -> None: ...
    def select(self, selector: str, *args: Any, **kwargs: Any) -> list[Any]: ...
    def select_one(self, selector: str, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_all(self, *args: Any, **kwargs: Any) -> list[Any]: ...
    def get_text(self, *args: Any, **kwargs: Any) -> str: ...
